/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn1"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted -pdu=all -D out`
 */

#ifndef	_LoadMeasurementID_H_
#define	_LoadMeasurementID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LoadMeasurementID */
typedef long	 LoadMeasurementID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadMeasurementID;
asn_struct_free_f LoadMeasurementID_free;
asn_struct_print_f LoadMeasurementID_print;
asn_constr_check_f LoadMeasurementID_constraint;
ber_type_decoder_f LoadMeasurementID_decode_ber;
der_type_encoder_f LoadMeasurementID_encode_der;
xer_type_decoder_f LoadMeasurementID_decode_xer;
xer_type_encoder_f LoadMeasurementID_encode_xer;
oer_type_decoder_f LoadMeasurementID_decode_oer;
oer_type_encoder_f LoadMeasurementID_encode_oer;
per_type_decoder_f LoadMeasurementID_decode_uper;
per_type_encoder_f LoadMeasurementID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LoadMeasurementID_H_ */
#include "asn_internal.h"
