/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "./e2sim_asn1c_asn_v03_e2ap-container-v03.01.asn"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fincludes-quoted -D out`
 */

#ifndef	_ProtocolIE_ContainerList_H_
#define	_ProtocolIE_ContainerList_H_


#include "asn_application.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_ContainerList_H_ */
#include "asn_internal.h"
