/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn1"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted -pdu=all -D out`
 */

#ifndef	_RICassistanceMessage_H_
#define	_RICassistanceMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICassistanceMessage */
typedef OCTET_STRING_t	 RICassistanceMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICassistanceMessage;
asn_struct_free_f RICassistanceMessage_free;
asn_struct_print_f RICassistanceMessage_print;
asn_constr_check_f RICassistanceMessage_constraint;
ber_type_decoder_f RICassistanceMessage_decode_ber;
der_type_encoder_f RICassistanceMessage_encode_der;
xer_type_decoder_f RICassistanceMessage_decode_xer;
xer_type_encoder_f RICassistanceMessage_encode_xer;
oer_type_decoder_f RICassistanceMessage_decode_oer;
oer_type_encoder_f RICassistanceMessage_encode_oer;
per_type_decoder_f RICassistanceMessage_decode_uper;
per_type_encoder_f RICassistanceMessage_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICassistanceMessage_H_ */
#include "asn_internal.h"
