/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn1"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted -pdu=all -D out`
 */

#ifndef	_RICassistanceHeader_H_
#define	_RICassistanceHeader_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICassistanceHeader */
typedef OCTET_STRING_t	 RICassistanceHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICassistanceHeader;
asn_struct_free_f RICassistanceHeader_free;
asn_struct_print_f RICassistanceHeader_print;
asn_constr_check_f RICassistanceHeader_constraint;
ber_type_decoder_f RICassistanceHeader_decode_ber;
der_type_encoder_f RICassistanceHeader_encode_der;
xer_type_decoder_f RICassistanceHeader_decode_xer;
xer_type_encoder_f RICassistanceHeader_encode_xer;
oer_type_decoder_f RICassistanceHeader_decode_oer;
oer_type_encoder_f RICassistanceHeader_encode_oer;
per_type_decoder_f RICassistanceHeader_decode_uper;
per_type_encoder_f RICassistanceHeader_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICassistanceHeader_H_ */
#include "asn_internal.h"
