/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "./e2sim_asn1c_asn_v03_e2ap-ied-v03.01.asn"
 * 	`asn1c -gen-PER -fcompound-names -findirect-choice -fincludes-quoted -D out`
 */

#ifndef	_RICqueryDefinition_H_
#define	_RICqueryDefinition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICqueryDefinition */
typedef OCTET_STRING_t	 RICqueryDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICqueryDefinition;
asn_struct_free_f RICqueryDefinition_free;
asn_struct_print_f RICqueryDefinition_print;
asn_constr_check_f RICqueryDefinition_constraint;
ber_type_decoder_f RICqueryDefinition_decode_ber;
der_type_encoder_f RICqueryDefinition_encode_der;
xer_type_decoder_f RICqueryDefinition_decode_xer;
xer_type_encoder_f RICqueryDefinition_encode_xer;
oer_type_decoder_f RICqueryDefinition_decode_oer;
oer_type_encoder_f RICqueryDefinition_encode_oer;
per_type_decoder_f RICqueryDefinition_decode_uper;
per_type_encoder_f RICqueryDefinition_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICqueryDefinition_H_ */
#include "asn_internal.h"
