/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn1"
 * 	`asn1c -gen-PER -fcompound-names -fincludes-quoted -pdu=all -D out`
 */

#ifndef	_RICsubscriptionAuditFlag_H_
#define	_RICsubscriptionAuditFlag_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ListedRecordsOnly.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICsubscriptionAuditFlag */
typedef struct RICsubscriptionAuditFlag {
	ListedRecordsOnly_t	*listedRecordsOnly	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICsubscriptionAuditFlag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICsubscriptionAuditFlag;

#ifdef __cplusplus
}
#endif

#endif	/* _RICsubscriptionAuditFlag_H_ */
#include "asn_internal.h"
